import os

API_KEY = os.getenv("API_KEY")

ACCESS_TOKEN = os.getenv("ACCESS_TOKEN")

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")

CHAT_ID = os.getenv("CHAT_ID")

CAPITAL = 50000

MAX_RISK_PERCENT = 2

MAX_LOSS_ALLOWED = CAPITAL * MAX_RISK_PERCENT / 100

INDEX_MAP = {
    "NIFTY": "NSE:NIFTY 50",
    "BANKNIFTY": "NSE:NIFTY BANK",
    "FINNIFTY": "NSE:NIFTY FIN SERVICE"
}

COMMODITY_LIST = [
    "CRUDEOIL",
    "GOLD",
    "SILVER"
]
